language: cpp
compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libboost-test-dev python-pip
  - sudo pip install cpplint

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: 
  - make
  - ctest -V
  - cd ..
  - cpplint --repository ./examplelib/include --recursive ./examplelib
  - cpplint --recursive ./examplebin
  - cpplint --recursive ./tests



