language: cpp
sudo: required
env:
  global:
    - HOMEBREW_DEPENDENCIES_XCODE6="doxygen valgrind zeromq"
    - HOMEBREW_DEPENDENCIES_XCODE10="doxygen zeromq"
    - APT_DEPENDENCIES_UBUNTU="libboost1.58-dev libboost-test1.58-dev libboost1.58-tools-dev valgrind gcc-8 g++-8 libzmq3-dev doxygen"
matrix: 
  include:
    - name: "Ubuntu 16.04 gcc-8"
      os: linux
      dist: xenial
      compiler:
        - gcc
      before_install:
        - date -u
        - uname -a
        - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test;
        - sudo apt update
        - sudo apt install $APT_DEPENDENCIES_UBUNTU
        - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 90;
        - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 90;
        - gcc --version
        - g++ --version
        - mkdir build
        - cd build
        - cmake -DCMAKE_BUILD_TYPE=Debug ../
      script:
        - make examplebin
        - valgrind --leak-check=full --show-leak-kinds=all --error-exitcode=1 examplebin