language: cpp
sudo: required
env:
  global:
    - HOMEBREW_DEPENDENCIES_XCODE6="doxygen valgrind zeromq"
    - HOMEBREW_DEPENDENCIES_XCODE10="doxygen zeromq"
    - APT_DEPENDENCIES_UBUNTU="libboost1.58-dev libboost-test1.58-dev libboost1.58-tools-dev valgrind gcc-8 g++-8 libzmq3-dev doxygen"
matrix: 
  include:
    - name: "Ubuntu 16.04 gcc-8"
      os: linux
      dist: xenial
      compiler:
        - gcc
      before_install:
        - date -u
        - uname -a
        - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test;
        - sudo apt update
        - sudo apt install $APT_DEPENDENCIES_UBUNTU
        - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 90;
        - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 90;
        - gcc --version
        - g++ --version
        - mkdir build
        - cd build
        - cmake -DCMAKE_BUILD_TYPE=Debug ../
      script:
        - make lib
        - make bin
        - make tests
        - make test
        - valgrind --leak-check=full --show-leak-kinds=all --error-exitcode=1 bin/bin
    - name: "Xcode 6.4 clang"
      os: osx
      osx_image: xcode6.4
      compiler:
        - clang
      before_install:
        - date -u
        - brew update
        - brew install $HOMEBREW_DEPENDENCIES_XCODE6
        - gcc --version
        - g++ --version
        - PROJECT_DIR=`pwd`
        - git clone https://github.com/zeromq/cppzmq.git
        - cd cppzmq
        - git fetch --all --tags --prune
        - git checkout v4.2.3
        - mkdir build
        - cd build
        - cmake ../
        - sudo make install
        - cd $PROJECT_DIR
        - >-
          PATH=$PATH:/usr/local/include:/usr/local/lib/
        - mkdir build
        - cd build
        - cmake -DCMAKE_BUILD_TYPE=Debug ../
      script:
        - make lib
        - make bin
        - make tests
        - make test
        - valgrind --leak-check=full --show-leak-kinds=all --error-exitcode=1 bin/bin
    - name: "Xcode 10 clang"
      os: osx
      osx_image: xcode10
      compiler:
        - clang
      before_install:
        - date -u
        - brew update
        - brew install $HOMEBREW_DEPENDENCIES_XCODE10
        - gcc --version
        - g++ --version
        - PROJECT_DIR=`pwd`
        - git clone https://github.com/zeromq/cppzmq.git
        - cd cppzmq
        - git fetch --all --tags --prune
        - git checkout v4.2.3
        - mkdir build
        - cd build
        - cmake ../
        - sudo make install
        - cd $PROJECT_DIR
        - >-
          PATH=$PATH:/usr/local/include:/usr/local/lib
        - mkdir build
        - cd build
        - cmake -DCMAKE_BUILD_TYPE=Debug ../
      script:
        - make lib
        - make bin
        - make tests
        - make test
    - name: "Docker centos 7.5 gcc-4.8"
      os: linux
      services: docker
      before_install:
        - INSTANCE_ID=`docker create -t -i centos:7.5.1804`
        - docker cp docker-centos.sh $INSTANCE_ID:/docker-centos.sh
        - docker start $INSTANCE_ID
      script:
        - docker exec -e REPO_URL=`git config --get remote.origin.url` $INSTANCE_ID bash docker-centos.sh